-- Esquema do WebGIS.
--
-- Consolida as dez migrations do desenvolvimento em um estado inicial unico. O
-- caminho ate aqui — o proprietario que era coluna de texto, a geometria que ja
-- foi coluna gerada, os dois numeros de encolhimento da trava de sobreposicao —
-- esta contado em backend/REFATORACAO.md; aqui fica so o resultado, que e' o
-- que um banco novo precisa saber.
--
-- Deve espelhar exatamente as entidades JPA: spring.jpa.hibernate.ddl-auto=validate
-- compara as duas descricoes na subida e recusa a aplicacao se divergirem.

-- ---------------------------------------------------------------------------
-- Extensoes
--
-- unaccent e pg_trgm sustentam a busca textual insensivel a acento. postgis nao
-- e' extensao "trusted": o CREATE exige superusuario. Sem ela esta migration
-- falha e o backend nao sobe — de proposito, porque um schema pela metade seria
-- pior de diagnosticar.
CREATE EXTENSION IF NOT EXISTS unaccent;
CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE EXTENSION IF NOT EXISTS postgis;

-- ---------------------------------------------------------------------------
-- Funcoes

-- unaccent() nao e' IMMUTABLE (depende do dicionario configurado), entao nao
-- pode ser usada diretamente em indice. A forma de dois argumentos fixa o
-- dicionario, o que torna o wrapper deterministico e indexavel.
CREATE OR REPLACE FUNCTION sem_acento(texto text) RETURNS text
    LANGUAGE sql IMMUTABLE STRICT PARALLEL SAFE
AS $$ SELECT public.unaccent('public.unaccent', lower(texto)) $$;

-- O lote de quem informa largura e comprimento em vez de desenhar o contorno.
--
-- STRICT resolve o imovel sem dimensoes com elegancia: qualquer argumento nulo
-- devolve nulo, e a linha simplesmente fica sem geometria.
--
-- Convencoes deliberadas: o ponto informado e' o **centro** do lote, e o
-- retangulo e' alinhado aos eixos da projecao (largura no eixo leste-oeste,
-- comprimento no norte-sul). Lote rotacionado por azimute fica fora do escopo —
-- para esse caso existe o desenho vertice a vertice.
CREATE OR REPLACE FUNCTION lote_retangular(
        lat numeric, lon numeric, largura numeric, comprimento numeric)
    RETURNS geometry(POLYGON, 31982)
    LANGUAGE sql IMMUTABLE STRICT PARALLEL SAFE
AS $$
    SELECT ST_MakeEnvelope(
               ST_X(p) - largura / 2, ST_Y(p) - comprimento / 2,
               ST_X(p) + largura / 2, ST_Y(p) + comprimento / 2,
               31982)
    FROM (SELECT ST_Transform(ST_SetSRID(ST_MakePoint(lon, lat), 4326), 31982) AS p) s;
$$;

COMMENT ON FUNCTION lote_retangular IS
    'Retangulo do lote em SIRGAS 2000 / UTM 22S, a partir do centro e das dimensoes em metros.';

-- ---------------------------------------------------------------------------
-- Proprietario
--
-- Quem identifica a pessoa e' o CPF, e so ele. O nome **nao** e' unico: dois
-- homonimos com documentos diferentes sao duas pessoas, e o cadastro precisa
-- conseguir guardar as duas.
CREATE TABLE proprietario (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome          VARCHAR(120)             NOT NULL,
    cpf           VARCHAR(11),
    criado_em     TIMESTAMP WITH TIME ZONE NOT NULL,
    atualizado_em TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_proprietario_cpf UNIQUE (cpf)
);

-- Guardado so em digitos: a pontuacao e' formatacao de tela, e duas grafias do
-- mesmo documento ("111.444.777-35" e "11144477735") passariam pelo UNIQUE como
-- se fossem pessoas diferentes. A aplicacao normaliza antes de gravar; esta
-- CHECK fecha os outros caminhos.
ALTER TABLE proprietario
    ADD CONSTRAINT ck_proprietario_cpf_digitos
    CHECK (cpf IS NULL OR cpf ~ '^[0-9]{11}$');

-- Nulo continua sendo aceito, e no Postgres o UNIQUE aceita varios nulos: e' o
-- que permite carregar um cadastro anterior a exigencia do documento. Dar CPF a
-- essas linhas e' ato explicito da aplicacao (PATCH /api/proprietarios/{id}/cpf),
-- nunca deducao a partir de nome igual.
COMMENT ON COLUMN proprietario.nome IS
    'Como a pessoa e chamada. Nao identifica: homonimos com CPFs diferentes sao registros distintos.';
COMMENT ON COLUMN proprietario.cpf IS
    'CPF apenas com digitos, e a identidade do proprietario.';

CREATE INDEX idx_proprietario_nome ON proprietario (nome);

-- GIN com trigramas: e' o unico tipo de indice que atende LIKE '%termo%'. Um
-- B-tree comum so serve para prefixo ('termo%'), inutil na busca da tela.
CREATE INDEX idx_proprietario_nome_busca
    ON proprietario USING gin (sem_acento(nome) gin_trgm_ops);

-- ---------------------------------------------------------------------------
-- Imovel
CREATE TABLE imovel (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proprietario_id BIGINT                   NOT NULL,
    cep             VARCHAR(8),
    municipio       VARCHAR(120)             NOT NULL,
    uf              VARCHAR(2)               NOT NULL,
    bairro          VARCHAR(100),
    rua             VARCHAR(150),
    numero          VARCHAR(10),
    latitude        NUMERIC(10, 7)           NOT NULL,
    longitude       NUMERIC(10, 7)           NOT NULL,
    area_m2         NUMERIC(12, 2),
    largura         NUMERIC(10, 2),
    comprimento     NUMERIC(10, 2),
    geom            geometry(POLYGON, 31982),
    ativo           BOOLEAN                  NOT NULL,
    criado_em       TIMESTAMP WITH TIME ZONE NOT NULL,
    atualizado_em   TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_imovel_proprietario FOREIGN KEY (proprietario_id) REFERENCES proprietario (id)
);

-- CEP guardado so em digitos, pelo mesmo motivo do CPF: a pontuacao e'
-- formatacao de tela, e "01452-000" e "01452000" sao o mesmo endereco. A
-- aplicacao normaliza antes de gravar; esta CHECK fecha os outros caminhos.
--
-- Opcional: o imovel rural ou o lote sem logradouro nao tem CEP, e exigi-lo
-- impediria o cadastro de existir.
ALTER TABLE imovel
    ADD CONSTRAINT ck_imovel_cep_digitos
    CHECK (cep IS NULL OR cep ~ '^[0-9]{8}$');

-- Dimensoes: opcionais, e indivisiveis. Meia dimensao nao gera retangulo, e
-- deixar passar criaria um estado que a aplicacao teria de tratar para sempre.
ALTER TABLE imovel
    ADD CONSTRAINT ck_imovel_dimensoes_completas
    CHECK ((largura IS NULL) = (comprimento IS NULL));

ALTER TABLE imovel
    ADD CONSTRAINT ck_imovel_dimensoes_positivas
    CHECK (largura IS NULL OR (largura > 0 AND comprimento > 0));

-- Anel aberto, com menos de quatro posicoes ou auto-interseccao ("gravata
-- borboleta") sao poligonos que o Postgres aceita guardar e o ST_Area calcula
-- errado. A aplicacao ja recusa antes; esta CHECK fecha os outros caminhos.
ALTER TABLE imovel
    ADD CONSTRAINT ck_imovel_geom_valida
    CHECK (geom IS NULL OR ST_IsValid(geom));

-- O ponto do imovel tem que cair no proprio lote. Sem isto, editar so a
-- latitude deixaria o marcador do mapa em uma cidade e o poligono em outra.
--
-- Tolerancia de 0,5 m, e nao ST_Contains exato, por dois motivos: o ponto e'
-- gravado em NUMERIC(10,7), o que ja arredonda cerca de 1 cm, e para lote
-- concavo (terreno em L) a aplicacao usa ST_PointOnSurface, cujo resultado
-- reprojetado ida e volta nao volta exatamente sobre o mesmo pixel.
ALTER TABLE imovel
    ADD CONSTRAINT ck_imovel_ponto_dentro_do_lote
    CHECK (geom IS NULL OR ST_DWithin(
        geom,
        ST_Transform(ST_SetSRID(ST_MakePoint(longitude, latitude), 4326), 31982),
        0.5));

-- A trava contra sobreposicao, e o encolhimento de 1,5 m que ela usa.
--
-- O numero nao e' arbitrario: o operador && compara bounding boxes, e o PostGIS
-- guarda essas caixas em float4. Na magnitude das coordenadas UTM daqui o passo
-- do float4 chega a **0,5 m** no northing (~7.190.000), entao dois lotes que
-- apenas dividem a divisa — o caso mais comum de um cadastro — seriam recusados
-- com encolhimento menor. Medido com dois lotes de ~53 ha lado a lado: com
-- 0,6 m o gap real entre as geometrias encolhidas era de 0,189 m, menor que o
-- arredondamento do indice. Com 1,5 m sobra cerca de 1 m depois dele.
--
-- **O que se perde:** a constraint deixa de acusar sobreposicoes menores que
-- ~3 m, e lote com menos de 3 m em qualquer direcao fica de fora dela (o
-- ST_Buffer negativo devolve geometria vazia). Aceitavel porque ela nunca foi a
-- checagem principal: quem recusa o cadastro com mensagem util e' o
-- VerificarSobreposicao, comparando a geometria exata em dupla precisao. O papel
-- daqui e' fechar a corrida entre duas requisicoes simultaneas, que nenhuma
-- checagem em SELECT resolve.
ALTER TABLE imovel
    ADD CONSTRAINT uk_imovel_sem_sobreposicao
    EXCLUDE USING gist (ST_Buffer(geom, -1.5) WITH &&);

-- Sustenta a busca "imoveis deste proprietario".
CREATE INDEX idx_imovel_proprietario_id ON imovel (proprietario_id);

CREATE INDEX idx_imovel_municipio_busca
    ON imovel USING gin (sem_acento(municipio) gin_trgm_ops);

-- Entra pelo caso que a tela produz: UF **combinada** com municipio ou
-- proprietario, onde o planejador pode cruzar este indice com o GIN de
-- trigramas por bitmap AND. Sozinho, no filtro de UF isolado, ele nao ganha —
-- sao no maximo 27 valores. Tambem permite percorrer o indice em vez da tabela
-- na consulta que monta o select de estados (GROUP BY uf).
CREATE INDEX idx_imovel_uf ON imovel (uf);

CREATE INDEX idx_imovel_geom ON imovel USING gist (geom);

-- ---------------------------------------------------------------------------
-- Carga inicial de exemplo.
--
-- Sem guarda de idempotencia: o Flyway registra esta migration na
-- flyway_schema_history e nunca a reexecuta. "Rodar uma vez" e' garantia da
-- ferramenta, nao responsabilidade do script.
--
-- Os doze proprietarios entram **sem CPF**, de proposito: e' o cadastro
-- anterior a exigencia do documento, e e' com ele que se exercita o caminho de
-- identificacao — editar um desses imoveis pede o CPF, e informa-lo vincula ao
-- registro que ja existe em vez de criar outro.
INSERT INTO proprietario (nome, criado_em, atualizado_em)
VALUES
    ('Maria Aparecida Souza',    NOW(), NOW()),
    ('João Carlos Ferreira',     NOW(), NOW()),
    ('Ana Beatriz Lima',         NOW(), NOW()),
    ('Carlos Eduardo Nunes',     NOW(), NOW()),
    ('Fernanda Ribeiro Alves',   NOW(), NOW()),
    ('Roberto Antunes Melo',     NOW(), NOW()),
    ('Patrícia Gomes Duarte',    NOW(), NOW()),
    ('Luiz Henrique Barbosa',    NOW(), NOW()),
    ('Juliana Martins Rocha',    NOW(), NOW()),
    ('Marcos Vinícius Teixeira', NOW(), NOW()),
    ('Camila Freitas Andrade',   NOW(), NOW()),
    ('Eduardo Pacheco Silva',    NOW(), NOW());

-- Ligados por nome no INSERT, e nao por id fixo: a coluna e' IDENTITY, e amarrar
-- o seed a 1..12 quebraria no dia em que alguem inserir uma linha antes. Sem
-- dimensoes, entao sem geometria — o lote de cada um e' desenhado na tela.
INSERT INTO imovel
    (proprietario_id, municipio, uf, bairro, rua, numero, latitude, longitude, area_m2, ativo, criado_em, atualizado_em)
SELECT p.id, s.municipio, s.uf, s.bairro, s.rua, s.numero, s.latitude, s.longitude, s.area_m2, TRUE, NOW(), NOW()
FROM (VALUES
    ('Maria Aparecida Souza',    'São Paulo',      'SP', 'Pinheiros',        'Rua dos Pinheiros',        '1245', -23.5629000, -46.6944000, 320.50),
    ('João Carlos Ferreira',     'São Paulo',      'SP', 'Santana',          'Avenida Braz Leme',        '890',  -23.5010000, -46.6280000, 450.00),
    ('Ana Beatriz Lima',         'Rio de Janeiro', 'RJ', 'Copacabana',       'Rua Barata Ribeiro',       '512',  -22.9686000, -43.1869000, 180.75),
    ('Carlos Eduardo Nunes',     'Rio de Janeiro', 'RJ', 'Tijuca',           'Rua Conde de Bonfim',      '1100', -22.9245000, -43.2340000, 210.00),
    ('Fernanda Ribeiro Alves',   'Belo Horizonte', 'MG', 'Savassi',          'Rua Pernambuco',           '77',   -19.9370000, -43.9350000, 265.30),
    ('Roberto Antunes Melo',     'Curitiba',       'PR', 'Batel',            'Avenida do Batel',         '1560', -25.4420000, -49.2920000, 390.00),
    ('Patrícia Gomes Duarte',    'Porto Alegre',   'RS', 'Moinhos de Vento', 'Rua Padre Chagas',         '340',  -30.0250000, -51.2050000, 155.60),
    ('Luiz Henrique Barbosa',    'Salvador',       'BA', 'Barra',            'Avenida Oceânica',         '2200', -13.0100000, -38.5330000, 275.90),
    ('Juliana Martins Rocha',    'Recife',         'PE', 'Boa Viagem',       'Avenida Boa Viagem',       '4500',  -8.1200000, -34.9000000, 198.40),
    ('Marcos Vinícius Teixeira', 'Fortaleza',      'CE', 'Aldeota',          'Avenida Santos Dumont',    '3131',  -3.7350000, -38.4950000, 340.00),
    ('Camila Freitas Andrade',   'Goiânia',        'GO', 'Setor Bueno',      'Rua T-55',                 '820',  -16.7050000, -49.2720000, 410.25),
    ('Eduardo Pacheco Silva',    'Florianópolis',  'SC', 'Campeche',         'Avenida Pequeno Príncipe', 'S/N',  -27.6780000, -48.4900000, 520.00)
) AS s(proprietario, municipio, uf, bairro, rua, numero, latitude, longitude, area_m2)
JOIN proprietario p ON p.nome = s.proprietario;
