-- Schema inicial do WebGIS.
-- Deve espelhar exatamente a entidade br.com.webgis.imovel.Imovel, porque
-- spring.jpa.hibernate.ddl-auto=validate compara os dois na subida.

CREATE TABLE imovel (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proprietario  VARCHAR(120)             NOT NULL,
    municipio     VARCHAR(120)             NOT NULL,
    uf            VARCHAR(2)               NOT NULL,
    bairro        VARCHAR(100),
    rua           VARCHAR(150),
    numero        VARCHAR(10),
    latitude      NUMERIC(10, 7)           NOT NULL,
    longitude     NUMERIC(10, 7)           NOT NULL,
    area_m2       NUMERIC(12, 2),
    ativo         BOOLEAN                  NOT NULL,
    criado_em     TIMESTAMP WITH TIME ZONE NOT NULL,
    atualizado_em TIMESTAMP WITH TIME ZONE NOT NULL
);

-- Suporta a ordenacao padrao da listagem (findAllByOrderByProprietarioAsc).
CREATE INDEX idx_imovel_proprietario ON imovel (proprietario);
