-- Normaliza o proprietario: de coluna de texto dentro de imovel para tabela propria.
--
-- A base ja tem imoveis cadastrados com o proprietario em texto, e nenhum pode
-- ser perdido. A sequencia abaixo e feita nesta ordem de proposito:
--   1. cria a tabela
--   2. extrai os nomes distintos que ja existem
--   3. religa cada imovel ao seu proprietario
--   4. so entao torna a coluna obrigatoria
--
-- O passo 4 e a rede de seguranca: se algum imovel tivesse ficado sem religacao,
-- o SET NOT NULL falha e a migration inteira sofre rollback. A falha e alta e
-- imediata, em vez de silenciosa.

CREATE TABLE proprietario (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome          VARCHAR(120)             NOT NULL,
    criado_em     TIMESTAMP WITH TIME ZONE NOT NULL,
    atualizado_em TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_proprietario_nome UNIQUE (nome)
);

-- Um proprietario por nome distinto ja existente na base.
INSERT INTO proprietario (nome, criado_em, atualizado_em)
SELECT DISTINCT proprietario, NOW(), NOW()
FROM imovel;

ALTER TABLE imovel ADD COLUMN proprietario_id BIGINT;

UPDATE imovel AS i
SET proprietario_id = p.id
FROM proprietario AS p
WHERE p.nome = i.proprietario;

-- Rede de seguranca: falha se algum imovel nao tiver sido religado.
ALTER TABLE imovel ALTER COLUMN proprietario_id SET NOT NULL;

ALTER TABLE imovel
    ADD CONSTRAINT fk_imovel_proprietario
    FOREIGN KEY (proprietario_id) REFERENCES proprietario (id);

-- Sustenta a busca "imoveis deste proprietario".
CREATE INDEX idx_imovel_proprietario_id ON imovel (proprietario_id);

-- Os indices de busca por nome mudam de tabela junto com a coluna.
DROP INDEX idx_imovel_proprietario_busca;
DROP INDEX idx_imovel_proprietario;

ALTER TABLE imovel DROP COLUMN proprietario;

CREATE INDEX idx_proprietario_nome ON proprietario (nome);

CREATE INDEX idx_proprietario_nome_busca
    ON proprietario USING gin (sem_acento(nome) gin_trgm_ops);
